mkdir to_deploy -p

cp website/beepbox_editor.min.js to_deploy/
cp website/service_worker.js to_deploy/
cp website/drumsamples.js to_deploy/
cp website/kirby_samples.js to_deploy/
cp website/samples.js to_deploy/
cp website/samples2.js to_deploy/
cp website/samples3.js to_deploy/
cp website/wario_samples.js to_deploy/
cp website/mario_paintbox_samples.js to_deploy/
cp website/nintaribox_samples.js to_deploy/
cp website/index.html to_deploy/
cp website/favicon.ico to_deploy/
cp website/icon_32.png to_deploy/
cp website/icon_maskable_192.png to_deploy/
cp website/404.html to_deploy/
cp website/credits.html to_deploy/
cp website/patch_notes.html to_deploy/
cp website/sample_extractor.html to_deploy/
cp website/beepbox_synth.min.js to_deploy/
cp website/synth_example.html to_deploy/
cp website/player/beepbox_player.min.js to_deploy/
cp website/player/drumsamples.js to_deploy/
cp website/player/kirby_samples.js to_deploy/
cp website/player/samples.js to_deploy/
cp website/player/samples2.js to_deploy/
cp website/player/samples3.js to_deploy/
cp website/player/wario_samples.js to_deploy/
cp website/player/mario_paintbox_samples.js to_deploy/
cp website/player/nintaribox_samples.js to_deploy/
cp website/player/index.html to_deploy/
cp website/player/404.html to_deploy/
cp website/theme_resources/AzurLaneThemeLogo.png to_deploy/
cp website/theme_resources/AzurLaneThemeMemoryTaskBackground.png to_deploy/
cp website/theme_resources/AzurLaneThemeMouse.png to_deploy/
cp website/theme_resources/AzurLaneThemeStarterSquad.png to_deploy/
cp website/theme_resources/abyssbox_border.png to_deploy/
cp website/theme_resources/abyssbox_border_light.png to_deploy/
cp website/theme_resources/abyssbox_cursor.png to_deploy/
cp website/theme_resources/abyssbox_cursor_hand.png to_deploy/
cp website/theme_resources/abysstype.otf to_deploy/
cp website/theme_resources/abysstype_small.otf to_deploy/
cp website/theme_resources/hotdog.png to_deploy/
cp website/theme_resources/icon-SelectAll.png to_deploy/
cp website/theme_resources/icon-copy.png to_deploy/
cp website/theme_resources/icon-deleteChannel.png to_deploy/
cp website/theme_resources/icon-duplicate.png to_deploy/
cp website/theme_resources/icon-edit.png to_deploy/
cp website/theme_resources/icon-export.png to_deploy/
cp website/theme_resources/icon-file.png to_deploy/
cp website/theme_resources/icon-fullscreen.png to_deploy/
cp website/theme_resources/icon-import.png to_deploy/
cp website/theme_resources/icon-insertChannel.png to_deploy/
cp website/theme_resources/icon-next.png to_deploy/
cp website/theme_resources/icon-paste.png to_deploy/
cp website/theme_resources/icon-pause.png to_deploy/
cp website/theme_resources/icon-play.png to_deploy/
cp website/theme_resources/icon-preferences.png to_deploy/
cp website/theme_resources/icon-prev.png to_deploy/
cp website/theme_resources/icon-record.png to_deploy/
cp website/theme_resources/icon-redo.png to_deploy/
cp website/theme_resources/icon-singleBarLoop.png to_deploy/
cp website/theme_resources/icon-speaker.png to_deploy/
cp website/theme_resources/icon-speakerMuted.png to_deploy/
cp website/theme_resources/icon-stop.png to_deploy/
cp website/theme_resources/icon-undo.png to_deploy/
cp website/theme_resources/icon-zoomIn.png to_deploy/
cp website/theme_resources/icon-zoomOut.png to_deploy/
cp website/theme_resources/moveNotesDown.png to_deploy/
cp website/theme_resources/moveNotesUp.png to_deploy/
cp website/theme_resources/stripesbg.gif to_deploy/
cp website/theme_resources/stripesbg_light.gif to_deploy/
cp website/theme_resources/wackybox_cursor.png to_deploy/